### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by cyberrep** [dougiteixeira/tuya#5]
Oi Douglas tudo bem, cara to tentando integrar minha fechadura tuya, e instaleu seu componente hoje.
Acho que precisa dar uma olhada, pois com alguma atualização do HA deu pau no código.

custom_components.tuya.number::TuyaNumberEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by dougiteixeira** [comment]
Nos meus testes não é apresentado nenhum erro...

Mas liberei uma nova versão atualizando o custom component com as recentes alterações da integração Tuya no core, incluindo as recentes alterações de padrão de desenvolvimento do Home Assistant.
